### ISSUE TITLE
"Page not found" for static files

### ISSUE THREAD

**Issue by Clasko** [seriousm4x/django-twitch-archive#51]
Hi,

i'm facing an issue with static files not loading.

Debug Output is the following:

    Using the URLconf defined in django-twitch-archive.urls, Django tried these URL patterns, in this order:

    admin/
    [name='index']
    top/week/ [name='topweek']
    top/month/ [name='topmonth']
    top/alltime/ [name='topalltime']
    search/ [name='search_results']
    stats/ [name='statistics']
    <slug:clip_id>/ [name='singleclip']
    ^media/(?P<path>.*)$

    The current path, static/css/all.min.css, didn't match any of these.

Output in console:

    dta-web | 0 static files copied to '/var/www/static', 149 unmodified.
    dta-web | Not Found: /static/css/all.min.css
    dta-web | Not Found: /favicon.ico
    dta-web | Not Found: /static/admin/css/nav_sidebar.css
    dta-web | Not Found: /static/admin/css/base.css
    dta-web | Not Found: /static/admin/js/nav_sidebar.js
    dta-web | Not Found: /static/admin/css/login.css
    dta-web | Not Found: /static/admin/css/responsive.css

This happens when accessing the Django application directly (no reverse proxy for now).

Any idea what is happing here?

**Comment by Clasko** [comment]
Ok, it seems this works currently only when the static files gets delivered from a own webserver. Is this a expected behavior?

**Comment by seriousm4x** [comment]
Yes, static files are only served by a dedicated webserver (like caddy or nginx) to handle many requests at once.

**Comment by Clasko** [comment]
Thanks for the confirmation. That wasn't clear at the beginning for me. Works like a charm now. Thanks for your work at this! :)
